syntax match green   "^\C\u\i\+"
syntax match yellow  "<leader>"
syntax match green   "<space>"
syntax match cyan    "<tab>"
syntax match cyan    "<enter>"
syntax match magenta "{motion}"
syntax match red     "<count>"
